In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sbn

In [2]:
df = pd.read_csv("datasets/first_datas.csv")

In [3]:
df.head()

country  height  weight  age gender
0      tr     130      30   10      e
1      tr     125      36   11      e
2      tr     135      34   10      k
3      tr     133      30    9      k
4      tr     129      38   12      e

In [4]:
df.tail()

country  height  weight  age gender
17      fr     187      80   27      e
18      fr     183      88   28      e
19      fr     159      40   29      k
20      fr     164      66   32      k
21      fr     166      56   42      k

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   country  22 non-null     object
 1   height   22 non-null     int64 
 2   weight   22 non-null     int64 
 3   age      22 non-null     int64 
 4   gender   22 non-null     object
dtypes: int64(3), object(2)
memory usage: 1008.0+ bytes


In [6]:
df.describe()

height      weight        age
count   22.000000   22.000000  22.000000
mean   163.363636   62.136364  28.681818
std     21.077059   22.286651  12.988590
min    125.000000   30.000000   9.000000
25%    156.000000   42.500000  22.250000
50%    165.500000   59.500000  28.500000
75%    179.250000   80.000000  38.000000
max    193.000000  105.000000  55.000000

In [7]:
#LabelEncoder - OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [8]:
labelEncoding = LabelEncoder()
country = labelEncoding.fit_transform(df["country"])
country

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0])

In [9]:
oneHotEncoding = OneHotEncoder()
country = oneHotEncoding.fit_transform(country.reshape(-1, 1)).toarray()
country

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [10]:
country = pd.DataFrame(country,columns=["fr","tr","us"],dtype="int")
country.head()

fr  tr  us
0   0   1   0
1   0   1   0
2   0   1   0
3   0   1   0
4   0   1   0

In [11]:
gender = labelEncoding.fit_transform(df["gender"])
gender

array([0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1])

In [12]:
gender = oneHotEncoding.fit_transform(gender.reshape(-1, 1)).toarray()
gender

array([[1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.]])

In [13]:
gender = pd.DataFrame(gender,columns=["e","k"],dtype="int")
gender.head()

e  k
0  1  0
1  1  0
2  0  1
3  0  1
4  1  0

In [14]:
df = df.drop("country",axis=1)
df = df.drop("gender",axis=1)

In [15]:
df.head()

height  weight  age
0     130      30   10
1     125      36   11
2     135      34   10
3     133      30    9
4     129      38   12

In [16]:
df = pd.concat([country,df],axis=1)
df = pd.concat([gender["e"],df],axis=1)

In [17]:
df.head()

e  fr  tr  us  height  weight  age
0  1   0   1   0     130      30   10
1  1   0   1   0     125      36   11
2  0   0   1   0     135      34   10
3  0   0   1   0     133      30    9
4  1   0   1   0     129      38   12

In [18]:
df = df.rename(columns={"e":"gender"})
df.head()    # Gender 1 -> man .....  Gender 0 -> woman

gender  fr  tr  us  height  weight  age
0       1   0   1   0     130      30   10
1       1   0   1   0     125      36   11
2       0   0   1   0     135      34   10
3       0   0   1   0     133      30    9
4       1   0   1   0     129      38   12

In [29]:
x = df.drop("gender",axis=1)
y = df["gender"]

In [30]:
#Gender Prediction
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.33,random_state=0)

In [32]:
x_train.shape

(14, 6)

In [33]:
y_train.shape

(14,)

In [34]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression()

In [35]:
y_predict = regressor.predict(x_test)
y_predict

array([ 0.98720204, -0.12036863,  0.05009703,  0.07137418,  0.72473935,
        0.64615044, -0.03567453,  0.32612171])

In [36]:
y_test 

20    0
10    0
14    0
13    0
1     1
21    0
11    0
19    0
Name: gender, dtype: int32

In [37]:
#Height Prediction

In [38]:
height = df["height"].values
height

array([130, 125, 135, 133, 129, 180, 190, 175, 177, 185, 165, 155, 160,
       162, 167, 174, 193, 187, 183, 159, 164, 166], dtype=int64)

In [40]:
x_height = df.drop("height",axis=1)
x_height.head()

gender  fr  tr  us  weight  age
0       1   0   1   0      30   10
1       1   0   1   0      36   11
2       0   0   1   0      34   10
3       0   0   1   0      30    9
4       1   0   1   0      38   12

In [42]:
x_train, x_test, y_train, y_test = train_test_split(x_height,height,test_size=0.33,random_state=0)

In [43]:
x_train.shape

(14, 6)

In [44]:
x_test.shape

(8, 6)

In [46]:
regressor2 = LinearRegression()
regressor2.fit(x_train,y_train)

LinearRegression()

In [47]:
height_predict = regressor2.predict(x_test)
height_predict

array([182.26638686, 152.87161474, 162.79386375, 158.30668577,
       130.82888952, 173.96138408, 150.12782663, 157.26898922])

In [48]:
y_test

array([164, 165, 167, 162, 125, 166, 155, 159], dtype=int64)

In [49]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test,height_predict)

7.335960043009848

In [55]:
#Backward elimination
import statsmodels.api as sm

In [56]:
X = np.append(arr= np.ones((22,1)).astype("int"), values=x_height, axis=1)

In [64]:
X_list = x_height.iloc[:,[0,1,2,3,4,5]].values
X_list = np.array(X_list,dtype=float)
model = sm.OLS(height,X_list).fit()
print(model.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.885
Model:                            OLS   Adj. R-squared:                  0.849
Method:                 Least Squares   F-statistic:                     24.69
Date:                Mon, 11 Apr 2022   Prob (F-statistic):           5.41e-07
Time:                        17:13:17   Log-Likelihood:                -73.950
No. Observations:                  22   AIC:                             159.9
Df Residuals:                      16   BIC:                             166.4
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1           -10.5980      5.052     -2.098      0.0

In [65]:
X_list = x_height.iloc[:,[0,1,2,3,4]].values
X_list = np.array(X_list,dtype=float)
model = sm.OLS(height,X_list).fit()
print(model.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.884
Model:                            OLS   Adj. R-squared:                  0.857
Method:                 Least Squares   F-statistic:                     32.47
Date:                Mon, 11 Apr 2022   Prob (F-statistic):           9.32e-08
Time:                        17:13:28   Log-Likelihood:                -74.043
No. Observations:                  22   AIC:                             158.1
Df Residuals:                      17   BIC:                             163.5
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1           -11.1093      4.733     -2.347      0.0

In [66]:
X_list = x_height.iloc[:,[1,2,3,4]].values
X_list = np.array(X_list,dtype=float)
model = sm.OLS(height,X_list).fit()
print(model.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.847
Model:                            OLS   Adj. R-squared:                  0.821
Method:                 Least Squares   F-statistic:                     33.16
Date:                Mon, 11 Apr 2022   Prob (F-statistic):           1.52e-07
Time:                        17:14:22   Log-Likelihood:                -77.131
No. Observations:                  22   AIC:                             162.3
Df Residuals:                      18   BIC:                             166.6
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1           119.8136      7.265     16.491      0.0