In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm

C:\Users\fb-du\anaconda3\lib\site-packages\statsmodels\tsa\base\tsa_model.py:7: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import (to_datetime, Int64Index, DatetimeIndex, Period,
C:\Users\fb-du\anaconda3\lib\site-packages\statsmodels\tsa\base\tsa_model.py:7: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import (to_datetime, Int64Index, DatetimeIndex, Period,


In [2]:
df = pd.read_csv("../datasets/weather_forecast.csv")
df

outlook  temperature  humidity  windy play
0      sunny           85        85  False   no
1      sunny           80        90   True   no
2   overcast           83        86  False  yes
3      rainy           70        96  False  yes
4      rainy           68        80  False  yes
5      rainy           65        70   True   no
6   overcast           64        65   True  yes
7      sunny           72        95  False   no
8      sunny           69        70  False  yes
9      rainy           75        80  False  yes
10     sunny           75        70   True  yes
11  overcast           72        90   True  yes
12  overcast           81        75  False  yes
13     rainy           71        91   True   no

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   outlook      14 non-null     object
 1   temperature  14 non-null     int64 
 2   humidity     14 non-null     int64 
 3   windy        14 non-null     bool  
 4   play         14 non-null     object
dtypes: bool(1), int64(2), object(2)
memory usage: 590.0+ bytes


In [4]:
df.describe()

temperature   humidity
count    14.000000  14.000000
mean     73.571429  81.642857
std       6.571667  10.285218
min      64.000000  65.000000
25%      69.250000  71.250000
50%      72.000000  82.500000
75%      78.750000  90.000000
max      85.000000  96.000000

In [5]:
df.corr()

temperature  humidity     windy
temperature     1.000000  0.315082 -0.328866
humidity        0.315082  1.000000 -0.201805
windy          -0.328866 -0.201805  1.000000

In [6]:
labelEncoding = LabelEncoder()
outlook = labelEncoding.fit_transform(df["outlook"])
outlook

array([2, 2, 0, 1, 1, 1, 0, 2, 2, 1, 2, 0, 0, 1])

In [7]:
ohe = OneHotEncoder()
outlook = ohe.fit_transform(outlook.reshape(-1, 1)).toarray()
outlook

array([[0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [8]:
outlook = pd.DataFrame(outlook,columns=["overcast","rainy","suny"],dtype="int")
df = df.drop("outlook",axis=1)
df = pd.concat([outlook,df],axis=1)

In [9]:
df.head()

overcast  rainy  suny  temperature  humidity  windy play
0         0      0     1           85        85  False   no
1         0      0     1           80        90   True   no
2         1      0     0           83        86  False  yes
3         0      1     0           70        96  False  yes
4         0      1     0           68        80  False  yes

In [10]:
windy = labelEncoding.fit_transform(df["windy"])
windy = pd.DataFrame(windy,columns=["windy"])

In [11]:
df = df.drop("windy",axis=1)
df = pd.concat([windy,df],axis=1)
df.head()

windy  overcast  rainy  suny  temperature  humidity play
0      0         0      0     1           85        85   no
1      1         0      0     1           80        90   no
2      0         1      0     0           83        86  yes
3      0         0      1     0           70        96  yes
4      0         0      1     0           68        80  yes

In [12]:
play = labelEncoding.fit_transform(df["play"])
play

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

In [13]:
play = pd.DataFrame(play,columns=["play"])
play.head()

play
0     0
1     0
2     1
3     1
4     1

In [14]:
df = df.drop("play",axis=1)
df = pd.concat([df,play],axis=1) 
df.head()

windy  overcast  rainy  suny  temperature  humidity  play
0      0         0      0     1           85        85     0
1      1         0      0     1           80        90     0
2      0         1      0     0           83        86     1
3      0         0      1     0           70        96     1
4      0         0      1     0           68        80     1

In [15]:
x = df.drop("play",axis=1)
y = df["play"]

In [16]:
x.head()

windy  overcast  rainy  suny  temperature  humidity
0      0         0      0     1           85        85
1      1         0      0     1           80        90
2      0         1      0     0           83        86
3      0         0      1     0           70        96
4      0         0      1     0           68        80

In [17]:
y.head()

0    0
1    0
2    1
3    1
4    1
Name: play, dtype: int32

In [18]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.33,random_state=0)

In [19]:
x_train.shape

(9, 6)

In [20]:
x_test.shape

(5, 6)

In [21]:
regressor =LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression()

In [22]:
predict = regressor.predict(x_test)

In [23]:
predict

array([0.74233631, 0.75371988, 0.78998557, 0.27181229, 0.78572451])

In [24]:
y_test

8     1
6     1
4     1
11    1
2     1
Name: play, dtype: int32

In [25]:
X = np.append(arr= np.ones((14,1)).astype("int"), values=x, axis=1)

In [26]:
X_list = x.iloc[:,[0,1,2,3,4,5]].values
X_list = np.array(X_list,dtype=float)
model = sm.OLS(y,X_list).fit()
print(model.summary())

                            OLS Regression Results                            
Dep. Variable:                   play   R-squared:                       0.483
Model:                            OLS   Adj. R-squared:                  0.160
Method:                 Least Squares   F-statistic:                     1.493
Date:                Mon, 11 Apr 2022   Prob (F-statistic):              0.292
Time:                        18:52:03   Log-Likelihood:                -4.9501
No. Observations:                  14   AIC:                             21.90
Df Residuals:                       8   BIC:                             25.73
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1            -0.4108      0.268     -1.533      0.1

C:\Users\fb-du\anaconda3\lib\site-packages\scipy\stats\stats.py:1541: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=14
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "
